# Generated by Django 3.0.5 on 2020-05-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anandi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bhaji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhaji_name', models.CharField(max_length=100)),
                ('bhaji_price', models.CharField(max_length=100)),
                ('bhaji_image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
