# Generated by Django 3.0.5 on 2020-05-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anandi', '0002_bhaji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_id', models.IntegerField(max_length=3)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(max_length=100)),
                ('price', models.IntegerField(max_length=3)),
            ],
        ),
    ]
