# Generated by Django 3.0.5 on 2020-05-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anandi', '0004_auto_20200526_0843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
