# Generated by Django 3.0.5 on 2020-05-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anandi', '0005_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_json', models.CharField(max_length=5000)),
                ('name', models.EmailField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.EmailField(max_length=100)),
                ('city', models.EmailField(max_length=100)),
                ('state', models.EmailField(max_length=100)),
                ('zip_code', models.EmailField(max_length=100)),
                ('phone', models.EmailField(max_length=100)),
            ],
        ),
    ]
