# Generated by Django 3.0.5 on 2020-05-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anandi', '0006_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhaji',
            name='category',
            field=models.CharField(default='bhaji', max_length=100),
        ),
    ]
