# Generated by Django 3.0.5 on 2020-05-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anandi', '0007_bhaji_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhaji',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
